---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yml
- deployments.yml
- services.yml
- volumes.yml
- secrets
- monitoring
- logging

# Custom Mereka-branded OpenEdX image
images:
  - name: docker.io/overhangio/openedx
    newName: asia-southeast1-docker.pkg.dev/mereka-lms/openedx/openedx
    newTag: 20260206-footer-css-05fabf8

# namespace to deploy all Resources to
namespace: mereka-lms

# annotations added to all Resources
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/commonannotations/
commonAnnotations:
  app.kubernetes.io/version: 18.2.2

# labels (and label selectors) added to all Resources
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/labels/
labels:
  - pairs:
      app.kubernetes.io/instance: mereka-lms
      app.kubernetes.io/part-of: mereka-lms
      app.kubernetes.io/managed-by: tutor
    includeSelectors: true


configMapGenerator:
- name: caddy-config
  files:
  - apps/caddy/Caddyfile
  options:
    labels:
        app.kubernetes.io/name: caddy
- name: openedx-settings-lms
  files:
  - apps/openedx/settings/lms/__init__.py
  - apps/openedx/settings/lms/development.py
  - apps/openedx/settings/lms/production.py
  - apps/openedx/settings/lms/test.py
  - apps/openedx/settings/lms/mereka_platform_admin.py
  - apps/openedx/settings/lms/mereka_multisite.py
  options:
    labels:
        app.kubernetes.io/name: openedx
- name: openedx-settings-cms
  files:
  - apps/openedx/settings/cms/__init__.py
  - apps/openedx/settings/cms/development.py
  - apps/openedx/settings/cms/production.py
  - apps/openedx/settings/cms/test.py
  - apps/openedx/settings/cms/mereka_platform_admin.py
  - apps/openedx/settings/cms/mereka_multisite.py
  options:
    labels:
        app.kubernetes.io/name: openedx
- name: openedx-config
  files:
  - apps/openedx/config/cms.env.yml
  - apps/openedx/config/lms.env.yml
  options:
    labels:
        app.kubernetes.io/name: openedx
- name: openedx-uwsgi-config
  files:
  - apps/openedx/uwsgi.ini
  options:
    labels:
        app.kubernetes.io/name: openedx
- name: openedx-theme-head-extra
  files:
  - apps/openedx/theme/head-extra.html
  options:
    labels:
        app.kubernetes.io/name: openedx
- name: redis-config
  files:
  - apps/redis/redis.conf
  options:
    labels:
        app.kubernetes.io/name: redis
- name: discovery-settings
  files:
    - plugins/discovery/apps/settings/tutor/production.py
    - plugins/discovery/apps/settings/tutor/mereka_platform_admin.py
- name: credentials-settings
  files:
  - plugins/credentials/apps/credentials/settings/__init__.py
  - plugins/credentials/apps/credentials/settings/development.py
  - plugins/credentials/apps/credentials/settings/production.py
  - plugins/credentials/apps/credentials/settings/mereka_platform_admin.py
- name: ecommerce-settings
  files:
  - plugins/ecommerce/apps/ecommerce/settings/__init__.py
  - plugins/ecommerce/apps/ecommerce/settings/development.py
  - plugins/ecommerce/apps/ecommerce/settings/paymentprocessors.json
  - plugins/ecommerce/apps/ecommerce/settings/production.py
  - plugins/ecommerce/apps/ecommerce/settings/mereka_platform_admin.py
- name: ecommerce-worker-settings
  files:
  - plugins/ecommerce/apps/ecommerce-worker/settings/__init__.py
  - plugins/ecommerce/apps/ecommerce-worker/settings/production.py
- name: mfe-caddy-config
  files:
    - plugins/mfe/apps/mfe/Caddyfile
  options:
    labels:
        app.kubernetes.io/name: mfe
- name: notes-settings
  files:
    - plugins/notes/apps/settings/tutor.py
- name: xqueue-settings
  files:
    - plugins/xqueue/apps/settings/tutor.py
