---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - promtail-rbac.yaml
  - promtail-configmap.yaml
  - promtail-daemonset.yaml
  - promtail-service.yaml

commonLabels:
  app.kubernetes.io/part-of: mereka-lms
  app.kubernetes.io/managed-by: kustomize
