---
apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: mereka-lms
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: log-forwarder
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9080
      targetPort: http-metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: promtail
