---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp
  labels:
    app.kubernetes.io/instance: mereka-lms
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/name: smtp
    app.kubernetes.io/part-of: mereka-lms
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mereka-lms
      app.kubernetes.io/managed-by: tutor
      app.kubernetes.io/name: smtp
      app.kubernetes.io/part-of: mereka-lms
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mereka-lms
        app.kubernetes.io/managed-by: tutor
        app.kubernetes.io/name: smtp
        app.kubernetes.io/part-of: mereka-lms
    spec:
      securityContext:
        runAsUser: 100
        runAsGroup: 101
      containers:
        - name: smtp
          image: docker.io/devture/exim-relay:4.96-r1-0
          ports:
            - containerPort: 8025
          env:
            - name: SMARTHOST
              value: "email-smtp.ap-southeast-1.amazonaws.com::587"
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ses-smtp-credentials
                  key: RELAY_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ses-smtp-credentials
                  key: RELAY_PASSWORD
            - name: HOSTNAME
              value: "mail.academyv2.mereka.io"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
          livenessProbe:
            tcpSocket:
              port: 8025
            initialDelaySeconds: 5
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 8025
            initialDelaySeconds: 5
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
