---
apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    app.kubernetes.io/name: discovery
    app.kubernetes.io/instance: mereka-lms
    app.kubernetes.io/part-of: mereka-lms
    app.kubernetes.io/managed-by: tutor
spec:
  type: NodePort
  ports:
    - port: 8000
      name: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: discovery
