---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-payments
  labels:
    app.kubernetes.io/name: postgresql-payments
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: mereka-lms
    app.kubernetes.io/part-of: mereka-lms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
