"""
Minimal Python test suite for mereka-lms.

This is an infrastructure/deployment repo, so most verification is done via
shell scripts. These tests cover the Python utilities that are testable in CI
without a live cluster.
"""


def test_pyproject_structure():
    """Verify pyproject.toml can be parsed and has required keys."""
    import tomllib
    from pathlib import Path

    root = Path(__file__).parent.parent
    pyproject_path = root / "pyproject.toml"

    assert pyproject_path.exists(), "pyproject.toml must exist at repo root"

    with open(pyproject_path, "rb") as f:
        data = tomllib.load(f)

    assert "project" in data, "pyproject.toml must have [project] section"
    assert "name" in data["project"], "[project] must have name"
    assert "requires-python" in data["project"], "[project] must declare requires-python"


def test_requirements_lock_exists():
    """Verify requirements.lock is present (generated by uv)."""
    from pathlib import Path

    root = Path(__file__).parent.parent
    lockfile = root / "requirements.lock"

    assert lockfile.exists(), (
        "requirements.lock must exist. Generate with: uv pip compile pyproject.toml -o requirements.lock"
    )
    content = lockfile.read_text()
    assert "autogenerated by uv" in content, "requirements.lock must be uv-generated"


def test_services_kajabi_webhook_importable():
    """Verify the kajabi-webhook service module has no import-time syntax errors."""
    import importlib.util
    from pathlib import Path

    main_py = Path(__file__).parent.parent / "services" / "kajabi-webhook" / "main.py"
    assert main_py.exists(), "services/kajabi-webhook/main.py must exist"

    spec = importlib.util.spec_from_file_location("kajabi_webhook_main", main_py)
    assert spec is not None, "Could not create module spec for kajabi-webhook main.py"
    # Just verify the spec loads without error (don't execute - has startup side effects)
