---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mereka-lms

resources:
  - admin-portal-deployment.yaml
  - admin-portal-service.yaml
  - learner-portal-deployment.yaml
  - learner-portal-service.yaml

configMapGenerator:
  - name: enterprise-admin-portal-caddy-config
    files:
      - Caddyfile=admin-portal-Caddyfile
    options:
      labels:
        app.kubernetes.io/name: enterprise-admin-portal
  - name: enterprise-learner-portal-caddy-config
    files:
      - Caddyfile=learner-portal-Caddyfile
    options:
      labels:
        app.kubernetes.io/name: enterprise-learner-portal
  - name: enterprise-mfe-env
    files:
      - env.config.js=enterprise-mfe-env.js
    options:
      labels:
        app.kubernetes.io/component: enterprise
