apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-mfe
  namespace: mereka-lms
  labels:
    app.kubernetes.io/name: enterprise-mfe
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: admin.academyv2.mereka.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: enterprise.academyv2.mereka.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
  tls:
    - hosts:
        - admin.academyv2.mereka.io
        - enterprise.academyv2.mereka.io
      secretName: enterprise-mfe-tls
