apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mereka-lms

resources:
  - ../../base
  - ingress-openedx-lms.yaml
  - ingress-openedx-mfe.yaml
  - ingress-openedx-studio.yaml

# Production-specific configurations

# Image tags for production (use specific SHA or version)
images:
  - name: docker.io/overhangio/openedx
    newName: asia-southeast1-docker.pkg.dev/mereka-lms/openedx/openedx
    newTag: 20260206-branding-overrides-2
  - name: openedx-mfe
    newName: asia-southeast1-docker.pkg.dev/mereka-lms/openedx/openedx-mfe
    newTag: production

# Production replica counts (higher for availability)
replicas:
  - name: lms
    count: 2
  - name: cms
    count: 1
  - name: lms-worker
    count: 2
  - name: cms-worker
    count: 1
