#!/usr/bin/env bash
# @covers AC-003
# @spec: ci-cd-pipeline_spec.md
# Shared CI skip guards — source this in verification scripts to gracefully
# skip checks whose prerequisites are absent (tutor_env, exports, kubectl, etc.).
# lint: allow-no-euo (sourced helper; must not mutate caller shell options)
#
# Usage:
#   source "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/scripts/shared/ci-skip-guards.sh"
#   require_tutor_env   || exit 0
#   require_command yq   || exit 0
#   require_directory exports/kajabi "Kajabi export data" || exit 0

# ── Helpers ────────────────────────────────────────────────────────────────

# Auto-detect repo root (works even when sourced from nested scripts)
: "${REPO_ROOT:=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"

_skip() {
  echo "[SKIP] $1" >&2
  return 1  # caller uses `|| exit 0`
}

# ── Guards ─────────────────────────────────────────────────────────────────

# Require tutor_env/ to exist (generated by the governed Tutor config wrapper)
require_tutor_env() {
  [[ -d "${REPO_ROOT}/tutor_env" ]] || _skip "tutor_env/ not generated - run './scripts/infra/tutor-config-save.sh' first"
}

# Require a directory to exist (e.g. exports/kajabi)
require_directory() {
  local dir="$1"
  local label="${2:-$dir}"
  # Support both absolute and relative paths
  if [[ "$dir" = /* ]]; then
    [[ -d "$dir" ]] || _skip "${label} directory missing: $dir"
  else
    [[ -d "${REPO_ROOT}/${dir}" ]] || _skip "${label} directory missing: ${dir}"
  fi
}

# Require a file to exist
require_file() {
  local file="$1"
  local label="${2:-$file}"
  if [[ "$file" = /* ]]; then
    [[ -f "$file" ]] || _skip "${label} file missing: $file"
  else
    [[ -f "${REPO_ROOT}/${file}" ]] || _skip "${label} file missing: ${file}"
  fi
}

# Require a command to be installed
require_command() {
  local cmd="$1"
  command -v "$cmd" >/dev/null 2>&1 || _skip "'$cmd' not installed"
}

# Require kubectl access to a cluster
require_kubectl() {
  command -v kubectl >/dev/null 2>&1 || _skip "kubectl not installed"
  kubectl cluster-info >/dev/null 2>&1 || _skip "no Kubernetes cluster reachable"
}

# Require a URL to be reachable (3s timeout)
require_url_reachable() {
  local url="$1"
  local label="${2:-$url}"
  command -v curl >/dev/null 2>&1 || _skip "curl not installed"
  curl -sf --connect-timeout 3 --max-time 5 -o /dev/null "$url" || _skip "${label} not reachable: $url"
}
