---
apiVersion: v1
kind: Service
metadata:
  name: badgr-server
  labels:
    app.kubernetes.io/name: badgr-server
    app.kubernetes.io/component: badges
    app.kubernetes.io/instance: mereka-lms
    app.kubernetes.io/part-of: mereka-lms
spec:
  type: ClusterIP
  ports:
    - port: 8150
      name: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: badgr-server
