---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-catalog
  labels:
    app.kubernetes.io/name: enterprise-catalog
    app.kubernetes.io/component: enterprise
    app.kubernetes.io/instance: mereka-lms
    app.kubernetes.io/part-of: mereka-lms
spec:
  type: ClusterIP
  ports:
    - port: 8160
      name: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: enterprise-catalog
