---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - enterprise-catalog-deployment.yaml
  - enterprise-catalog-service.yaml
  - enterprise-subsidy-deployment.yaml
  - enterprise-subsidy-service.yaml
  - enterprise-access-deployment.yaml
  - enterprise-access-service.yaml
  - license-manager-deployment.yaml
  - license-manager-service.yaml
  - workers/enterprise-catalog-worker-deployment.yaml
  - workers/enterprise-access-worker-deployment.yaml
  - mfe
