apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: bbi-k8
      secretVersionSelectionPolicy: LatestOrFail
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secret-manager
            key: key.json
            namespace: external-secrets
        workloadIdentity: null
