apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
spec:
  template:
    spec:
      containers:
        - name: cms
          resources:
            limits:
              memory: 7Gi
            requests:
              memory: 2Gi
