apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
  labels:
    app.kubernetes.io/name: lms
spec:
  template:
    spec:
      containers:
        - name: lms
          env:
            - name: MEREKA_LMS_DOMAIN
              value: academyv2.mereka.dev
            - name: MEREKA_SCHEME
              value: https
            - name: MEREKA_COOKIE_DOMAIN
              value: .academyv2.mereka.dev
            - name: LMS_BASE_URL
              value: https://academyv2.mereka.dev
            - name: MFE_BASE_URL
              value: https://apps.academyv2.mereka.dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  labels:
    app.kubernetes.io/name: cms
spec:
  template:
    spec:
      containers:
        - name: cms
          env:
            - name: MEREKA_LMS_DOMAIN
              value: academyv2.mereka.dev
            - name: MEREKA_SCHEME
              value: https
            - name: MEREKA_COOKIE_DOMAIN
              value: .academyv2.mereka.dev
            - name: LMS_BASE_URL
              value: https://academyv2.mereka.dev
            - name: MFE_BASE_URL
              value: https://apps.academyv2.mereka.dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-worker
  labels:
    app.kubernetes.io/name: lms-worker
spec:
  template:
    spec:
      containers:
        - name: lms-worker
          env:
            - name: MEREKA_LMS_DOMAIN
              value: academyv2.mereka.dev
            - name: MEREKA_SCHEME
              value: https
            - name: MEREKA_COOKIE_DOMAIN
              value: .academyv2.mereka.dev
            - name: LMS_BASE_URL
              value: https://academyv2.mereka.dev
            - name: MFE_BASE_URL
              value: https://apps.academyv2.mereka.dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-worker
  labels:
    app.kubernetes.io/name: cms-worker
spec:
  template:
    spec:
      containers:
        - name: cms-worker
          env:
            - name: MEREKA_LMS_DOMAIN
              value: academyv2.mereka.dev
            - name: MEREKA_SCHEME
              value: https
            - name: MEREKA_COOKIE_DOMAIN
              value: .academyv2.mereka.dev
            - name: LMS_BASE_URL
              value: https://academyv2.mereka.dev
            - name: MFE_BASE_URL
              value: https://apps.academyv2.mereka.dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
  labels:
    app.kubernetes.io/name: discovery
spec:
  template:
    spec:
      containers:
        - name: discovery
          env:
            - name: MEREKA_LMS_DOMAIN
              value: academyv2.mereka.dev
            - name: MEREKA_SCHEME
              value: https
            - name: LMS_BASE_URL
              value: https://academyv2.mereka.dev
            - name: MFE_BASE_URL
              value: https://apps.academyv2.mereka.dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce
  labels:
    app.kubernetes.io/name: ecommerce
spec:
  template:
    spec:
      containers:
        - name: ecommerce
          env:
            - name: MEREKA_LMS_DOMAIN
              value: academyv2.mereka.dev
            - name: MEREKA_SCHEME
              value: https
            - name: LMS_BASE_URL
              value: https://academyv2.mereka.dev
            - name: MFE_BASE_URL
              value: https://apps.academyv2.mereka.dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-worker
  labels:
    app.kubernetes.io/name: ecommerce-worker
spec:
  template:
    spec:
      containers:
        - name: ecommerce-worker
          env:
            - name: MEREKA_LMS_DOMAIN
              value: academyv2.mereka.dev
            - name: MEREKA_SCHEME
              value: https
            - name: LMS_BASE_URL
              value: https://academyv2.mereka.dev
            - name: MFE_BASE_URL
              value: https://apps.academyv2.mereka.dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
  labels:
    app.kubernetes.io/name: notes
spec:
  template:
    spec:
      containers:
        - name: notes
          env:
            - name: MEREKA_LMS_DOMAIN
              value: academyv2.mereka.dev
            - name: NOTES_DOMAIN
              value: notes.academyv2.mereka.dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credentials
  labels:
    app.kubernetes.io/name: credentials
spec:
  template:
    spec:
      containers:
        - name: credentials
          env:
            - name: MEREKA_LMS_DOMAIN
              value: academyv2.mereka.dev
            - name: MEREKA_MFE_DOMAIN
              value: apps.academyv2.mereka.dev
            - name: MEREKA_CREDENTIALS_DOMAIN
              value: credentials.academyv2.mereka.dev
            - name: MEREKA_SCHEME
              value: https
            - name: LMS_BASE_URL
              value: https://academyv2.mereka.dev
            - name: MFE_BASE_URL
              value: https://apps.academyv2.mereka.dev
