apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openedx-secrets
  namespace: mereka-lms
spec:
  data:
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: MEREKA_LMS_STRIPE_SECRET_KEY_DEV
    - secretKey: STRIPE_PUBLISHABLE_KEY
      remoteRef:
        key: MEREKA_LMS_STRIPE_PUBLISHABLE_KEY_DEV
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: MEREKA_LMS_STRIPE_WEBHOOK_SECRET_DEV
