#!/usr/bin/env python3
"""Generate specs/INDEX.md from the lane-aware spec catalog."""

import argparse
import json
import sys
from pathlib import Path


def load_catalog(path: Path) -> list[dict]:
    data = json.loads(path.read_text())
    entries = data.get("entries", [])
    if not isinstance(entries, list):
        raise ValueError("specs/catalog.json entries must be a list")
    return entries


def render_section(title: str, entries: list[dict]) -> list[str]:
    lines = [
        f"## {title}",
        "",
        "| # | Title | Lane | Class | Status | Version | ACs | Reviewed |",
        "|---|-------|------|-------|--------|---------|-----|----------|",
    ]
    for i, entry in enumerate(entries, 1):
        path = entry["path"].replace("specs/", "", 1)
        lines.append(
            f"| {i} | [{entry['title']}]({path}) | {entry.get('lane', '—')} | "
            f"{entry.get('spec_class', '—')} | {entry.get('status', '—')} | "
            f"{entry.get('version', '—')} | {entry.get('acceptance_criteria_count', 0)} | "
            f"{entry.get('last_reviewed', '—')} |"
        )
    lines.append("")
    return lines


def render_index(specs_dir: Path) -> str:
    """Generate the INDEX.md content."""
    entries = load_catalog(specs_dir / "catalog.json")
    total_acs = sum(int(entry.get("acceptance_criteria_count", 0)) for entry in entries)

    # Count by status
    status_counts = {}
    lane_counts = {}
    doc_type_counts = {}
    for entry in entries:
        s = entry.get("status", "—")
        status_counts[s] = status_counts.get(s, 0) + 1
        lane = entry.get("lane", "unknown")
        lane_counts[lane] = lane_counts.get(lane, 0) + 1
        doc_type = entry.get("doc_type", "unknown")
        doc_type_counts[doc_type] = doc_type_counts.get(doc_type, 0) + 1

    lines = [
        "# Specification Index",
        "",
        f"> Auto-generated by `render_index.py`. **{len(entries)} lane-tracked items**, **{total_acs} acceptance criteria**.",
        "> Machine-readable companion catalog: [catalog.json](catalog.json)",
        "",
        "## Summary",
        "",
    ]

    for status, count in sorted(status_counts.items(), key=lambda item: str(item[0])):
        lines.append(f"- **{status}**: {count} items")
    for lane, count in sorted(lane_counts.items(), key=lambda item: str(item[0])):
        lines.append(f"- **lane:{lane}**: {count} items")
    for doc_type, count in sorted(doc_type_counts.items(), key=lambda item: str(item[0])):
        lines.append(f"- **type:{doc_type}**: {count} items")
    lines.append("")

    sections = [
        (
            "Normative Specs",
            [
                e
                for e in entries
                if e.get("lane") == "normative" and e.get("doc_type") != "generated"
            ],
        ),
        ("Proposal Specs", [e for e in entries if e.get("lane") == "proposal"]),
        ("Plans", [e for e in entries if e.get("lane") == "plan"]),
        ("Test Plans", [e for e in entries if e.get("lane") == "testplan"]),
        (
            "Compatibility Wrappers",
            [e for e in entries if e.get("doc_type") == "generated"],
        ),
    ]
    for title, section_entries in sections:
        if section_entries:
            lines.extend(render_section(title, section_entries))

    lines.extend([
        "",
        "## Related Surfaces",
        "",
        "- [Spec system charter](standards/SPEC_SYSTEM_CHARTER.md)",
        "- [Docs/specs boundary](standards/DOCS_SPECS_BOUNDARY.md)",
        "- [Active proposals](proposals/README.md)",
        "- [Active plans](plans/README.md)",
        "- [Generated testmaps](_generated/testmaps/README.md)",
        "",
        "---",
        "",
        f"*Generated from {len(entries)} lane-tracked items. Total ACs: {total_acs}.*",
    ])

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate specs/INDEX.md from frontmatter")
    parser.add_argument("--output", "-o", default="specs/INDEX.md", help="Output file path")
    parser.add_argument("--specs-dir", default="specs", help="Specs directory")
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout instead of writing")
    parser.add_argument("--check", action="store_true", help="Fail if output differs from generated content")
    args = parser.parse_args()

    specs_dir = Path(args.specs_dir)
    if not specs_dir.exists():
        print(f"Error: {specs_dir} not found", file=sys.stderr)
        sys.exit(1)

    content = render_index(specs_dir)

    output_path = Path(args.output)

    if args.check:
        current = output_path.read_text() if output_path.exists() else None
        if current != content:
            print(f"SPEC_INDEX_DRIFT_FAIL output={args.output}", file=sys.stderr)
            sys.exit(1)
        print(f"SPEC_INDEX_OK output={args.output} mode=check")
    elif args.dry_run:
        print(content)
    else:
        output_path.write_text(content)
        print(f"Generated {args.output} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
