#!/usr/bin/env python3
"""Generate specs/INDEX.md from spec frontmatter.

Reads all specs/*_spec.md files, extracts YAML frontmatter, and generates
a sortable Markdown table with title, class, status, version, AC count, and last_reviewed.

Usage:
    python3 scripts/qa/spec-tools/render_index.py
    python3 scripts/qa/spec-tools/render_index.py --output specs/INDEX.md
"""

import argparse
import re
import sys
from pathlib import Path


def parse_frontmatter(filepath: Path) -> dict:
    """Extract YAML frontmatter from a spec file."""
    content = filepath.read_text()

    # Match YAML frontmatter between --- markers
    match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
    if not match:
        return {}

    fm = {}
    for line in match.group(1).splitlines():
        if ":" in line and not line.startswith(" ") and not line.startswith("-"):
            key, _, value = line.partition(":")
            fm[key.strip()] = value.strip().strip('"').strip("'")
    return fm


def count_acs(filepath: Path) -> int:
    """Count acceptance criteria (checkbox lines with AC- prefix)."""
    content = filepath.read_text()
    return len(re.findall(r"- \[ \] AC-", content))


def get_tier(filepath: Path, fm: dict) -> str:
    """Determine spec tier from frontmatter or filename patterns."""
    tier = fm.get("tier", "")
    if tier:
        return str(tier)

    # Heuristic: foundational specs are lower tier
    name = filepath.stem.replace("_spec", "")
    tier_map = {
        "cross-cutting-requirements": "0",
        "repository-structure": "1",
        "k8s-deployment": "1",
        "secrets-management": "1",
        "tutor-configuration": "2",
        "multi-site-domains": "2",
        "mongodb-atlas-integration": "2",
    }
    return tier_map.get(name, "—")


def render_index(specs_dir: Path) -> str:
    """Generate the INDEX.md content."""
    specs = sorted(specs_dir.glob("*_spec.md"))

    rows = []
    total_acs = 0

    for spec in specs:
        fm = parse_frontmatter(spec)
        ac_count = count_acs(spec)
        total_acs += ac_count
        tier = get_tier(spec, fm)

        rows.append({
            "file": spec.name,
            "title": fm.get("title", spec.stem),
            "spec_class": fm.get("spec_class", fm.get("type", "—")),
            "status": fm.get("status", "—"),
            "version": fm.get("version", "—"),
            "tier": tier,
            "acs": ac_count,
            "reviewed": fm.get("last_reviewed", fm.get("last_updated", "—")),
        })

    # Count by status
    status_counts = {}
    for r in rows:
        s = r["status"]
        status_counts[s] = status_counts.get(s, 0) + 1

    lines = [
        "# Specification Index",
        "",
        f"> Auto-generated by `render_index.py`. **{len(rows)} specs**, **{total_acs} acceptance criteria**.",
        "> Machine-readable companion catalog: [catalog.json](catalog.json)",
        "",
        "## Summary",
        "",
    ]

    for status, count in sorted(status_counts.items()):
        lines.append(f"- **{status}**: {count} specs")
    lines.append("")

    lines.extend([
        "## Specs",
        "",
        "| # | Title | Class | Status | Version | Tier | ACs | Reviewed |",
        "|---|-------|-------|--------|---------|------|-----|----------|",
    ])

    for i, r in enumerate(rows, 1):
        link = f"[{r['title']}]({r['file']})"
        lines.append(
            f"| {i} | {link} | {r['spec_class']} | {r['status']} | {r['version']} "
            f"| {r['tier']} | {r['acs']} | {r['reviewed']} |"
        )

    lines.extend([
        "",
        "## Related Surfaces",
        "",
        "- [Spec system charter](standards/SPEC_SYSTEM_CHARTER.md)",
        "- [Docs/specs boundary](standards/DOCS_SPECS_BOUNDARY.md)",
        "- [Active proposals](proposals/README.md)",
        "- [Active plans](plans/README.md)",
        "- [Generated testmaps](_generated/testmaps/README.md)",
        "",
        "---",
        "",
        f"*Generated from {len(rows)} spec files. Total ACs: {total_acs}.*",
    ])

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate specs/INDEX.md from frontmatter")
    parser.add_argument("--output", "-o", default="specs/INDEX.md", help="Output file path")
    parser.add_argument("--specs-dir", default="specs", help="Specs directory")
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout instead of writing")
    parser.add_argument("--check", action="store_true", help="Fail if output differs from generated content")
    args = parser.parse_args()

    specs_dir = Path(args.specs_dir)
    if not specs_dir.exists():
        print(f"Error: {specs_dir} not found", file=sys.stderr)
        sys.exit(1)

    content = render_index(specs_dir)

    output_path = Path(args.output)

    if args.check:
        current = output_path.read_text() if output_path.exists() else None
        if current != content:
            print(f"SPEC_INDEX_DRIFT_FAIL output={args.output}", file=sys.stderr)
            sys.exit(1)
        print(f"SPEC_INDEX_OK output={args.output} mode=check")
    elif args.dry_run:
        print(content)
    else:
        output_path.write_text(content)
        print(f"Generated {args.output} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
