"""Models for Video Content Protection"""
from django.conf import settings
from django.db import models
from django.utils import timezone
from opaque_keys.edx.django.models import CourseKeyField


class SignedPlaybackToken(models.Model):
    """
    Tracks generated signed playback tokens for audit and rate limiting.

    Mux signed URLs use JWT tokens with RSA-2048 signatures. This model
    provides audit trail and enables rate limiting (e.g., 100 tokens/hour/user).
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        db_index=True,
        help_text='User who requested the signed playback URL',
    )
    course_key = CourseKeyField(
        max_length=255,
        db_index=True,
        help_text='Course containing the video',
    )
    video_id = models.CharField(
        max_length=255,
        db_index=True,
        help_text='Mux playback ID (not asset ID)',
    )
    org_slug = models.CharField(
        max_length=100,
        db_index=True,
        default='',
        help_text='Organization slug for multi-tenant tracking',
    )
    token = models.TextField(
        help_text='JWT token (for audit purposes, not used for validation)',
    )
    expires_at = models.DateTimeField(
        db_index=True,
        help_text='Token expiration timestamp (UTC)',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text='When the token was generated',
    )
    ip_address_hash = models.CharField(
        max_length=64,
        null=True,
        blank=True,
        help_text='SHA-256 hash of IP address (privacy-first)',
    )
    user_agent = models.CharField(
        max_length=500,
        null=True,
        blank=True,
        help_text='Client user agent (truncated)',
    )

    class Meta:
        db_table = 'video_signed_playback_tokens'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', '-created_at']),
            models.Index(fields=['course_key', 'video_id', '-created_at']),
            models.Index(fields=['org_slug', '-created_at']),
            models.Index(fields=['expires_at']),
        ]
        verbose_name = 'Signed Playback Token'
        verbose_name_plural = 'Signed Playback Tokens'

    def __str__(self):
        return f'{self.user.username} - {self.video_id} (expires {self.expires_at})'

    @property
    def is_expired(self):
        """Check if token has expired"""
        return timezone.now() > self.expires_at

    @classmethod
    def cleanup_expired_tokens(cls, days_to_keep=7):
        """
        Delete expired tokens older than specified days.

        Args:
            days_to_keep: Keep tokens for this many days after expiry (audit trail)

        Returns:
            Number of tokens deleted
        """
        cutoff = timezone.now() - timezone.timedelta(days=days_to_keep)
        deleted_count, _ = cls.objects.filter(expires_at__lt=cutoff).delete()
        return deleted_count

    @classmethod
    def count_recent_tokens_for_user(cls, user, hours=1):
        """
        Count tokens generated by user in recent hours (for rate limiting).

        Args:
            user: User instance
            hours: Time window in hours

        Returns:
            Number of tokens generated
        """
        cutoff = timezone.now() - timezone.timedelta(hours=hours)
        return cls.objects.filter(user=user, created_at__gte=cutoff).count()


class VideoAccessLog(models.Model):
    """
    Audit log for video access attempts (both successful and denied).

    Tracks enrollment checks, feature flag status, and denial reasons.
    """

    ACCESS_GRANTED = 'granted'
    ACCESS_DENIED = 'denied'
    ACCESS_STATUS_CHOICES = [
        (ACCESS_GRANTED, 'Access Granted'),
        (ACCESS_DENIED, 'Access Denied'),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        db_index=True,
        null=True,
        blank=True,
        help_text='User who requested access (null for anonymous)',
    )
    course_key = CourseKeyField(
        max_length=255,
        db_index=True,
        help_text='Course containing the video',
    )
    video_id = models.CharField(
        max_length=255,
        db_index=True,
        help_text='Mux playback ID',
    )
    status = models.CharField(
        max_length=20,
        choices=ACCESS_STATUS_CHOICES,
        db_index=True,
        help_text='Access granted or denied',
    )
    denial_reason = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        help_text='Reason for denial (not_enrolled, feature_disabled, etc.)',
    )
    timestamp = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text='When access was requested',
    )
    ip_address_hash = models.CharField(
        max_length=64,
        null=True,
        blank=True,
        help_text='SHA-256 hash of IP address',
    )
    org_slug = models.CharField(
        max_length=100,
        db_index=True,
        default='',
        help_text='Organization slug',
    )

    class Meta:
        db_table = 'video_access_logs'
        ordering = ['-timestamp']
        indexes = [
            models.Index(fields=['user', '-timestamp']),
            models.Index(fields=['course_key', 'video_id', '-timestamp']),
            models.Index(fields=['status', '-timestamp']),
            models.Index(fields=['org_slug', '-timestamp']),
        ]
        verbose_name = 'Video Access Log'
        verbose_name_plural = 'Video Access Logs'

    def __str__(self):
        username = self.user.username if self.user else 'anonymous'
        return f'{username} - {self.video_id} - {self.status}'

    @classmethod
    def log_access(cls, user, course_key, video_id, status, denial_reason=None, **kwargs):
        """
        Log a video access attempt.

        Args:
            user: User instance (or None for anonymous)
            course_key: Course key
            video_id: Mux playback ID
            status: ACCESS_GRANTED or ACCESS_DENIED
            denial_reason: Optional reason for denial
            **kwargs: Additional fields (ip_address_hash, org_slug)

        Returns:
            VideoAccessLog instance
        """
        return cls.objects.create(
            user=user,
            course_key=course_key,
            video_id=video_id,
            status=status,
            denial_reason=denial_reason,
            ip_address_hash=kwargs.get('ip_address_hash'),
            org_slug=kwargs.get('org_slug', ''),
        )
