#!/usr/bin/env bash
# Setup OpenEdX iOS app for Mereka Academy
# Run this on your Mac with Xcode installed
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="${HOME}/Projects/mereka-ios-app"

echo "=== Mereka Academy iOS App Setup ==="
echo ""

# Check for Xcode
if ! xcode-select -p &>/dev/null; then
  echo "ERROR: Xcode not installed. Please install from the App Store."
  exit 1
fi
echo "✓ Xcode found"

# Check for CocoaPods
if ! command -v pod &>/dev/null; then
  echo "Installing CocoaPods..."
  sudo gem install cocoapods
fi
echo "✓ CocoaPods available"

# Clone repository
if [ -d "$APP_DIR" ]; then
  echo "Directory $APP_DIR already exists."
  read -p "Delete and re-clone? [y/N] " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    rm -rf "$APP_DIR"
  else
    cd "$APP_DIR"
    git pull
  fi
fi

if [ ! -d "$APP_DIR" ]; then
  echo "Cloning OpenEdX iOS app..."
  git clone https://github.com/openedx/openedx-app-ios.git "$APP_DIR"
fi

cd "$APP_DIR"

# Install dependencies
echo ""
echo "Installing dependencies..."
pod install

# Create configuration
echo ""
echo "Creating Mereka Academy configuration..."

mkdir -p default_config/mereka

cat > default_config/mereka/config.yaml << 'EOF'
# Mereka Academy Mobile App Configuration
# Generated by setup-ios-app.sh
# Server configured: 2026-01-13

API_HOST_URL: "https://academyv2.mereka.io"
OAUTH_CLIENT_ID: "mereka-mobile-app"

# Note: Discovery service is for course catalog search
# Use empty string if not enabled
DISCOVERY_BASE_URL: ""

FEATURES:
  PRE_LOGIN_EXPERIENCE_ENABLED: false
  COURSE_NESTED_LIST_ENABLED: true
  COURSE_UNIT_PROGRESS_ENABLED: true
  COURSE_DATES_CALENDAR_SYNC: true
  WHAT_IS_NEW_ENABLED: true
  SOCIAL_AUTH_ENABLED: true

GOOGLE:
  ENABLED: false

MICROSOFT:
  ENABLED: false

FACEBOOK:
  ENABLED: false

APPLE_SIGNIN:
  ENABLED: true

SEGMENT_IO:
  ENABLED: false
  
FIREBASE:
  ENABLED: false

BRAZE:
  ENABLED: false

BRANCH:
  ENABLED: false

AGREEMENT_URLS:
  PRIVACY_POLICY_URL: "https://academyv2.mereka.io/privacy"
  TOS_URL: "https://academyv2.mereka.io/tos"
  EULA_URL: ""
  DATA_SELL_CONSENT_URL: ""
  SUPPORTED_LANGUAGES: []
  
FEEDBACK_EMAIL: "team@mereka.io"

THEME:
  PRIMARY_COLOR: "#1A1A2E"
  ACCENT_COLOR: "#E94560"
EOF

cat > default_config/mereka/config_settings.yaml << 'EOF'
config_directory: "mereka"
config_mapping:
  prod: "config.yaml"
  stage: "config.yaml"
  dev: "config.yaml"
EOF

echo "✓ Configuration created"

# Create xcconfig for build settings
cat > OpenEdX/Config/MerekaConfig.xcconfig << 'EOF'
// Mereka Academy Build Configuration
CONFIG_DIRECTORY = mereka
PRODUCT_BUNDLE_IDENTIFIER = com.mereka.academy.mobile
PRODUCT_NAME = Mereka Academy
EOF

echo "✓ Xcode configuration created"
echo ""
echo "=== Setup Complete! ==="
echo ""
echo "Next steps:"
echo "1. Open Xcode: open $APP_DIR/OpenEdX.xcworkspace"
echo "2. Select the 'OpenEdX' target"
echo "3. Go to Build Settings → find 'User-Defined'"
echo "4. Add: CONFIG_DIRECTORY = mereka"
echo "5. Change Bundle Identifier to: com.mereka.academy.mobile"
echo "6. Select your Apple Developer Team"
echo "7. Connect your iPhone and press Cmd+R to build & run"
echo ""
echo "For TestFlight deployment:"
echo "1. Product → Archive"
echo "2. Click 'Distribute App' → App Store Connect"
echo "3. Upload, then go to appstoreconnect.apple.com"
echo "4. Add yourself as internal tester"
echo ""

# Open project in Xcode
read -p "Open project in Xcode now? [Y/n] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
  open OpenEdX.xcworkspace
fi
