# Generated by Django 6.0.3 on 2026-03-29 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(db_index=True, help_text='ACE message type (e.g., course_announcement, assignment_reminder)', max_length=50)),
                ('title', models.CharField(help_text='Notification title (shown in notification bell)', max_length=255)),
                ('body', models.TextField(help_text='Notification body text (supports Markdown)')),
                ('course_id', models.CharField(blank=True, db_index=True, help_text='Course ID (if notification is course-specific)', max_length=255, null=True)),
                ('org_slug', models.CharField(db_index=True, help_text='Organization slug for multi-tenancy isolation', max_length=255)),
                ('deep_link_url', models.URLField(blank=True, help_text='Deep link URL for mobile apps and MFE navigation', max_length=1024, null=True)),
                ('read', models.BooleanField(db_index=True, default=False, help_text='Whether the notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the notification was created (UTC)')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When the notification expires and should not be shown (UTC)', null=True)),
                ('user', models.ForeignKey(help_text='Recipient user', on_delete=django.db.models.deletion.CASCADE, related_name='openedx_in_app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'openedx_notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', 'created_at'], name='openedx_not_user_id_2efe23_idx'), models.Index(fields=['user', 'org_slug', 'read'], name='openedx_not_user_id_b75774_idx'), models.Index(fields=['expires_at'], name='openedx_not_expires_7205f6_idx')],
            },
        ),
    ]
