---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - servicemonitor-lms.yaml
  - servicemonitor-cms.yaml
  - servicemonitor-mysql.yaml
  - servicemonitor-redis.yaml
  - prometheusrule-lms.yaml
