---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - servicemonitor-lms.yaml
  - servicemonitor-cms.yaml
  - servicemonitor-mysql.yaml
  - servicemonitor-redis.yaml
  - servicemonitor-enterprise.yaml
  - servicemonitor-xqueue.yaml
  - prometheusrule-lms.yaml
  - prometheusrule-enterprise.yaml
  - prometheusrule-xqueue.yaml
  - prometheusrule-velero.yaml
  - prometheusrule-slo.yaml
  - prometheusrule-auth.yaml
  - prometheusrule-email.yaml
  - prometheusrule-video.yaml
  - prometheusrule-libraries.yaml
  - mux-exporter.yaml
  - servicemonitor-mux.yaml
  - hpa-enterprise.yaml
