---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: credentials-metrics
  namespace: mereka-lms
  labels:
    app.kubernetes.io/name: credentials
    app.kubernetes.io/instance: mereka-lms
    app.kubernetes.io/part-of: mereka-lms
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: credentials
      app.kubernetes.io/part-of: mereka-lms
  namespaceSelector:
    matchNames:
      - mereka-lms
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
      podRelabelings:
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
        - action: replace
          sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
