---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-metrics
  namespace: mereka-lms
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mereka-lms
    app.kubernetes.io/part-of: mereka-lms
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  namespaceSelector:
    matchNames:
      - mereka-lms
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
