#!/usr/bin/env bash
set -euo pipefail

# Runtime theme-generation script.
# Produces the four files required by PARAGON_THEME_URLS:
# - core.min.css (Paragon core baseline)
# - light.min.css (light-variant delta)
# - mereka-brand.min.css (brand delta against core)
# - mereka-brand-light.min.css (brand delta for light variant)
#
# Usage:
#   ./scripts/branding/build-tokens.sh
#   ./scripts/branding/build-tokens.sh --check
#     - Verifies tracked runtime theme artifacts match deterministic regeneration.
#     - Uses tracked core.min.css as the deterministic baseline for delta generation.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TOKENS_SCSS="$REPO_ROOT/infrastructure/tutor/themes/mereka/scss/_tokens.scss"
OUTPUT_DIR="$REPO_ROOT/infrastructure/tutor/themes/mereka/mfe/theme"
CHECK_ONLY=0

for arg in "$@"; do
  case "$arg" in
    --check)
      CHECK_ONLY=1
      ;;
    -h|--help)
      cat <<'EOF'
Usage: build-tokens.sh [--check]

Generate or validate PARAGON_THEME_URLS runtime theme artifacts.
EOF
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      exit 1
      ;;
  esac
done

mkdir -p "$OUTPUT_DIR"

if [[ ! -f "$TOKENS_SCSS" ]]; then
  echo "ERROR: missing token source $TOKENS_SCSS" >&2
  exit 1
fi

write_core_theme() {
  local target="$1"
  local core_sources=(
    "$REPO_ROOT/node_modules/@edx/paragon/dist/css/core.min.css"
    "$REPO_ROOT/node_modules/@edx/paragon/dist/css/core.css"
    "$REPO_ROOT/node_modules/@openedx/paragon/dist/css/core.min.css"
    "$REPO_ROOT/node_modules/@openedx/paragon/dist/css/core.css"
  )

  local copied=0
  for candidate in "${core_sources[@]}"; do
    if [[ -f "$candidate" ]]; then
      cp "$candidate" "$target"
      copied=1
      break
    fi
  done

  if [[ "$copied" -eq 1 ]]; then
    return
  fi

  python3 - "$target" <<'PY'
from pathlib import Path
import io
import json
import sys
import tarfile
import urllib.request

output = Path(sys.argv[1])
registry_url = "https://registry.npmjs.org/@openedx/paragon"

try:
    with urllib.request.urlopen(registry_url, timeout=15) as response:
        metadata = json.load(response)
except Exception:
    raise SystemExit(1)

version = metadata.get("dist-tags", {}).get("latest")
if not version:
    raise SystemExit(1)

version_payload = metadata.get("versions", {}).get(version, {})
tarball_url = version_payload.get("dist", {}).get("tarball")
if not tarball_url:
    raise SystemExit(1)

try:
    with urllib.request.urlopen(tarball_url, timeout=30) as tarball_response:
        tar_data = tarball_response.read()
except Exception:
    raise SystemExit(1)

core_members = [
    "package/dist/core.min.css",
    "package/dist/core.css",
]

try:
    tar = tarfile.open(fileobj=io.BytesIO(tar_data), mode="r:gz")
except Exception:
    raise SystemExit(1)

for member in core_members:
    try:
        source = tar.extractfile(member)
    except (KeyError, AttributeError):
        source = None
    if source is not None:
        output.write_bytes(source.read())
        break
else:
    raise SystemExit(1)
PY

  if [[ "$?" -eq 0 && -s "$target" ]]; then
    return
  fi

  # Fallback: use the tracked core.min.css already in the repo (CI has no
  # node_modules and npm download may be blocked by network policy).
  local tracked_core="$OUTPUT_DIR/core.min.css"
  if [[ -s "$tracked_core" ]]; then
    cp "$tracked_core" "$target"
    return
  fi

  cat > "$target" <<'CSS'
:root {
  /* fallback core theme — no node_modules, no npm, no tracked copy */
}
CSS
}

write_light_delta_theme() {
  local target="$1"
  cat > "$target" <<'CSS'
/* Generated by build-tokens.sh for PARAGON_THEME_URLS light variant delta. */
/* Light-mode only deployment: no additional light variant overrides required. */
:root {}
CSS
}

write_brand_delta_theme() {
  local tokens_scss="$1"
  local output_css="$2"
  local core_css="$3"

  python3 - "$tokens_scss" "$output_css" "$core_css" <<'PY'
from pathlib import Path
import re
import sys

path_tokens = Path(sys.argv[1])
path_brand = Path(sys.argv[2])
path_core = Path(sys.argv[3])

text = path_tokens.read_text(encoding="utf-8")
core_text = path_core.read_text(encoding="utf-8") if path_core.exists() else ""

var_def_re = re.compile(r"^\s*\$([A-Za-z0-9_-]+):\s*(.+?)\s*;\s*$")
var_ref_re = re.compile(r"#\{\$([A-Za-z0-9_-]+)\}")
var_plain_re = re.compile(r"\$([A-Za-z0-9_-]+)")
pgn_decl_re = re.compile(r"(--pgn-[A-Za-z0-9_-]+)\s*:\s*([^;{}]+)")

vars_map = {}
for line in text.splitlines():
    m = var_def_re.match(line)
    if m:
        vars_map[m.group(1)] = m.group(2)


def resolve_var(name: str, depth: int = 0) -> str:
    if depth > 32:
        return vars_map.get(name, f"#{{${name}}}")
    raw = vars_map.get(name)
    if raw is None:
        return f"#{{${name}}}"
    resolved = var_ref_re.sub(lambda m: resolve_var(m.group(1), depth + 1), raw)
    resolved = var_plain_re.sub(lambda m: resolve_var(m.group(1), depth + 1), resolved)
    return resolved


def normalize_value(raw: str) -> str:
    return re.sub(r"\s+", "", raw).lower()


root_match = re.search(r":root\s*\{(.*?)\n\}", text, re.S)
if not root_match:
    raise SystemExit("Unable to locate :root block in _tokens.scss")

desired_tokens = {}
for raw in root_match.group(1).splitlines():
    stripped = raw.strip()
    if not stripped.startswith("--pgn-") or ";" not in stripped:
        continue
    name, value = stripped.split(":", 1)
    value = value.strip().rstrip(";").strip()
    resolved = var_ref_re.sub(lambda m: resolve_var(m.group(1)), value)
    resolved = var_plain_re.sub(lambda m: resolve_var(m.group(1)), resolved)
    desired_tokens[name] = resolved.strip()

core_tokens = {}
for raw in re.finditer(pgn_decl_re, core_text):
    name = raw.group(1)
    value = raw.group(2).strip()
    if value:
        # Keep the last declaration seen.
        core_tokens[name] = value

consumed_tokens = set(
    re.findall(r"var\(\s*(--pgn-[A-Za-z0-9_-]+)\s*(?:,|\))", core_text)
)
token_ref_re = re.compile(r"var\(\s*(--pgn-[A-Za-z0-9_-]+)\b")

# Keep minimal dependency closure: if a consumed token's desired value references
# another --pgn-* token from our bridge, include that dependency too.
required_tokens = set(consumed_tokens)
queue = list(consumed_tokens)
while queue:
    token_name = queue.pop()
    desired_value = desired_tokens.get(token_name, "")
    if not desired_value:
        continue
    for dep in token_ref_re.findall(desired_value):
        if dep in desired_tokens and dep not in required_tokens:
            required_tokens.add(dep)
            queue.append(dep)

delta_lines = []
for name in sorted(desired_tokens):
    # Runtime brand delta should include:
    # 1) tokens Paragon core actually reads, and
    # 2) bridge dependencies referenced by those consumed tokens.
    if name not in required_tokens:
        continue
    desired = desired_tokens[name]
    current = core_tokens.get(name)
    if current is not None and normalize_value(current) == normalize_value(desired):
        continue
    delta_lines.append(f"  {name}: {desired};")

if not delta_lines:
    raise SystemExit("No --pgn-* delta properties detected against core.min.css")

payload = (
    "/* Generated by build-tokens.sh for PARAGON_THEME_URLS brand override delta. */\n"
    "/* Contains consumed --pgn-* values (plus dependency tokens) that differ from core. */\n"
    ":root {\n"
    + "\n".join(delta_lines)
    + "\n}\n"
)

path_brand.write_text(payload, encoding="utf-8")
path_brand.with_name("mereka-brand-light.min.css").write_text(payload, encoding="utf-8")
PY
}

check_mode() {
  local tracked_core="$OUTPUT_DIR/core.min.css"
  local tracked_light="$OUTPUT_DIR/light.min.css"
  local tracked_brand="$OUTPUT_DIR/mereka-brand.min.css"
  local tracked_brand_light="$OUTPUT_DIR/mereka-brand-light.min.css"

  for required in "$tracked_core" "$tracked_light" "$tracked_brand" "$tracked_brand_light"; do
    if [[ ! -f "$required" ]]; then
      echo "ERROR: missing tracked runtime theme artifact: $required" >&2
      echo "Run ./scripts/branding/build-tokens.sh to generate all runtime theme artifacts." >&2
      exit 1
    fi
  done

  local tmp_dir
  tmp_dir="$(mktemp -d)"
  trap "rm -rf '$tmp_dir'" EXIT

  cp "$tracked_core" "$tmp_dir/core.min.css"
  write_light_delta_theme "$tmp_dir/light.min.css"
  write_brand_delta_theme "$TOKENS_SCSS" "$tmp_dir/mereka-brand.min.css" "$tmp_dir/core.min.css"

  local drift=0
  if ! cmp -s "$tracked_light" "$tmp_dir/light.min.css"; then
    echo "DRIFT: light.min.css does not match generator output." >&2
    drift=1
  fi
  if ! cmp -s "$tracked_brand" "$tmp_dir/mereka-brand.min.css"; then
    echo "DRIFT: mereka-brand.min.css does not match generator output." >&2
    drift=1
  fi
  if ! cmp -s "$tracked_brand_light" "$tmp_dir/mereka-brand-light.min.css"; then
    echo "DRIFT: mereka-brand-light.min.css does not match generator output." >&2
    drift=1
  fi

  if [[ "$drift" -ne 0 ]]; then
    echo "FAIL: runtime theme artifact drift detected." >&2
    echo "Run ./scripts/branding/build-tokens.sh and commit regenerated files." >&2
    exit 1
  fi

  echo "Runtime theme artifacts are in sync."
}

if [[ "$CHECK_ONLY" -eq 1 ]]; then
  check_mode
  exit 0
fi

write_core_theme "$OUTPUT_DIR/core.min.css"
write_light_delta_theme "$OUTPUT_DIR/light.min.css"
write_brand_delta_theme "$TOKENS_SCSS" "$OUTPUT_DIR/mereka-brand.min.css" "$OUTPUT_DIR/core.min.css"

echo "Wrote theme assets to $OUTPUT_DIR"
