#!/usr/bin/env bash
set -euo pipefail

# Transitional runtime theme-generation script.
# Produces the four files required by PARAGON_THEME_URLS:
# - core.min.css
# - light.min.css
# - mereka-brand.min.css
# - mereka-brand-light.min.css

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TOKENS_SCSS="$REPO_ROOT/infrastructure/tutor/themes/mereka/scss/_tokens.scss"
OUTPUT_DIR="$REPO_ROOT/infrastructure/tutor/themes/mereka/mfe/theme"

mkdir -p "$OUTPUT_DIR"

if [[ ! -f "$TOKENS_SCSS" ]]; then
  echo "ERROR: missing token source $TOKENS_SCSS" >&2
  exit 1
fi

write_core_theme() {
  local target="$1"
  local core_sources=(
    "$REPO_ROOT/node_modules/@edx/paragon/dist/css/core.min.css"
    "$REPO_ROOT/node_modules/@edx/paragon/dist/css/core.css"
    "$REPO_ROOT/node_modules/@openedx/paragon/dist/css/core.min.css"
    "$REPO_ROOT/node_modules/@openedx/paragon/dist/css/core.css"
  )

  local copied=0
  for candidate in "${core_sources[@]}"; do
    if [[ -f "$candidate" ]]; then
      cp "$candidate" "$target"
      copied=1
      break
    fi
  done

  if [[ "$copied" -eq 1 ]]; then
    return
  fi

  python3 - "$target" <<'PY'
from pathlib import Path
import json
import io
import sys
import tarfile
import urllib.request

OUTPUT = Path(sys.argv[1])
registry_url = "https://registry.npmjs.org/@openedx/paragon"
try:
    with urllib.request.urlopen(registry_url, timeout=15) as response:
        metadata = json.load(response)
except Exception:
    raise SystemExit(1)

version = metadata.get("dist-tags", {}).get("latest")
if not version:
    raise SystemExit(1)

version_payload = metadata.get("versions", {}).get(version, {})
tarball_url = version_payload.get("dist", {}).get("tarball")
if not tarball_url:
    raise SystemExit(1)

try:
    with urllib.request.urlopen(tarball_url, timeout=30) as tarball_response:
        tar_data = tarball_response.read()
except Exception:
    raise SystemExit(1)

core_members = [
    "package/dist/core.min.css",
    "package/dist/core.css",
]

try:
    tar = tarfile.open(fileobj=io.BytesIO(tar_data), mode="r:gz")
except Exception:
    raise SystemExit(1)

for member in core_members:
    try:
        source = tar.extractfile(member)
    except (KeyError, AttributeError):
        source = None
    if source is not None:
        OUTPUT.write_bytes(source.read())
        break
else:
    raise SystemExit(1)
PY

  if [[ "$?" -eq 0 && -s "$target" ]]; then
    return
  fi

  cat > "$target" <<'CSS'
:root {
  /* fallback core theme */
}
CSS
}

write_core_theme "$OUTPUT_DIR/core.min.css"
cp "$OUTPUT_DIR/core.min.css" "$OUTPUT_DIR/light.min.css"

CORE_THEME="$OUTPUT_DIR/core.min.css"
python3 - "$TOKENS_SCSS" "$OUTPUT_DIR/mereka-brand.min.css" "$CORE_THEME" <<'PY'
from pathlib import Path
import re
import sys

PATH_TOKENS = Path(sys.argv[1])
PATH_BRAND = Path(sys.argv[2])
PATH_CORE = Path(sys.argv[3]) if len(sys.argv) > 3 else None

text = PATH_TOKENS.read_text(encoding="utf-8")

var_def_re = re.compile(r"^\s*\$([A-Za-z0-9_-]+):\s*(.+?)\s*;\s*$")
var_ref_re = re.compile(r"#\{\$([A-Za-z0-9_-]+)\}")
var_plain_re = re.compile(r"\$([A-Za-z0-9_-]+)")
pgn_decl_re = re.compile(r"(--pgn-[A-Za-z0-9_-]+)\s*:\s*([^;{}]+)")

vars = {}
for line in text.splitlines():
    m = var_def_re.match(line)
    if m:
        vars[m.group(1)] = m.group(2)


def resolve_var(name, depth=0):
    if depth > 32:
        return vars.get(name, f"#{{${name}}}")
    raw = vars.get(name)
    if raw is None:
        return f"#{{${name}}}"
    resolved = var_ref_re.sub(lambda m: resolve_var(m.group(1), depth + 1), raw)
    resolved = var_plain_re.sub(lambda m: resolve_var(m.group(1), depth + 1), resolved)
    return resolved


root_match = re.search(r":root\s*\{(.*?)\n\}", text, re.S)
if not root_match:
    raise SystemExit("Unable to locate :root block in _tokens.scss")

pgn_lines = []
seen = set()

for raw in root_match.group(1).splitlines():
    line = raw.rstrip()
    stripped = line.strip()
    if not stripped.startswith("--pgn-"):
        continue
    if ";" not in stripped:
        continue

    name, value = stripped.split(":", 1)
    value = value.strip()
    if value.endswith(";"):
        value = value[:-1].strip()

    resolved = var_ref_re.sub(lambda m: resolve_var(m.group(1)), value)
    resolved = var_plain_re.sub(lambda m: resolve_var(m.group(1)), resolved)

    seen.add(name)
    pgn_lines.append(f"  {name}: {resolved};")

core_text = ""
if PATH_CORE is not None and PATH_CORE.exists():
    core_text = PATH_CORE.read_text(encoding="utf-8")

if core_text:
    for raw in re.finditer(pgn_decl_re, core_text):
        name = raw.group(1)
        if name in seen:
            continue
        value = raw.group(2).strip()
        if not value:
            continue
        seen.add(name)
        pgn_lines.append(f"  {name}: {value.strip()};")

if not pgn_lines:
    raise SystemExit("No --pgn-* properties found in _tokens.scss")

payload = (
    "/* Generated by build-tokens.sh for PARAGON_THEME_URLS brand override. */\n"
    "/* The light variant is intentionally identical to this file while we remain light-mode only. */\n"
    ":root {\n"
    + "\n".join(pgn_lines)
    + "\n}\n"
)
PATH_BRAND.write_text(payload, encoding="utf-8")
PATH_BRAND.with_name("mereka-brand-light.min.css").write_text(payload, encoding="utf-8")
PY

echo "Wrote theme assets to $OUTPUT_DIR"
