# Staging hosts (DNS + cert-manager TLS).
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openedx-lms
  namespace: mereka-lms
  labels:
    app.kubernetes.io/name: openedx-lms
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: staging.academyv2.mereka.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: staging.preview.academyv2.mereka.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: staging.discovery.academyv2.mereka.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: staging.notes.academyv2.mereka.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: staging.credentials.academyv2.mereka.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
    - host: staging.forum.academyv2.mereka.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
  tls:
    - hosts:
        - staging.academyv2.mereka.io
        - staging.preview.academyv2.mereka.io
        - staging.discovery.academyv2.mereka.io
        - staging.notes.academyv2.mereka.io
        - staging.credentials.academyv2.mereka.io
        - staging.forum.academyv2.mereka.io
      secretName: staging-openedx-lms-tls
