# Staging Studio host.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openedx-studio
  namespace: mereka-lms
  labels:
    app.kubernetes.io/name: openedx-studio
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: staging.studio.academyv2.mereka.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
  tls:
    - hosts:
        - staging.studio.academyv2.mereka.io
      secretName: staging-openedx-studio-tls
