#!/usr/bin/env python3
"""Append docs compliance summary to GitHub step summary."""
import json
import sys

with open(sys.argv[1], "r", encoding="utf-8") as fp:
    payload = json.load(fp)

with open(sys.argv[2], "a", encoding="utf-8") as fp:
    foundation = payload.get("foundation_gates", {})
    command_refs = payload.get("command_refs", {})
    link_integrity = payload.get("link_integrity", {})
    foundation_status_content = payload.get('statuses', {}).get('foundation_policy_content', 'n/a')
    foundation_detail_content = foundation.get('policy_content_status', 'n/a')
    foundation_content_consistent = foundation.get('policy_content_consistent', 'n/a')
    foundation_alignment_status = payload.get('statuses', {}).get('foundation_policy_content_alignment', 'n/a')
    fp.write("### Docs Compliance Summary\n")
    fp.write(f"- overall_status={payload.get('overall_status')}\n")
    fp.write(f"- foundation_gates_status={payload.get('statuses', {}).get('foundation_gates', 'n/a')}\n")
    fp.write(f"- foundation_policy_status={payload.get('statuses', {}).get('foundation_policy', 'n/a')}\n")
    fp.write(f"- foundation_repo_structure_status={payload.get('statuses', {}).get('foundation_repo_structure', 'n/a')}\n")
    fp.write(f"- foundation_policy_content_status={foundation_status_content}\n")
    fp.write(f"- foundation_policy_content_consistency_status={payload.get('statuses', {}).get('foundation_policy_content_consistency', 'n/a')}\n")
    fp.write(f"- foundation_policy_content_alignment_status={foundation_alignment_status}\n")
    fp.write(f"- foundation_policy_range={foundation.get('policy_range', 'n/a')}\n")
    fp.write(f"- foundation_policy_root_allowlist_violations={foundation.get('policy_root_allowlist_violations', 'n/a')}\n")
    fp.write(f"- foundation_policy_changed_markdown_files={foundation.get('policy_changed_markdown_files', 'n/a')}\n")
    fp.write(f"- foundation_policy_content_detail={foundation_detail_content}\n")
    fp.write(f"- foundation_policy_content_consistency_aligned={str(foundation_alignment_status == 'pass').lower()}\n")
    fp.write(f"- foundation_policy_content_consistent={str(foundation_content_consistent).lower()}\n")
    fp.write(f"- foundation_policy_content_errors={len(foundation.get('policy_content_errors', []))}\n")
    fp.write(f"- command_reference_baseline_status={payload.get('statuses', {}).get('command_reference_baseline', 'n/a')}\n")
    fp.write(f"- catalog_health_status={payload.get('statuses', {}).get('catalog_health', 'n/a')}\n")
    fp.write(f"- link_integrity_status={payload.get('statuses', {}).get('link_integrity', 'n/a')}\n")
    fp.write(f"- link_integrity_files_checked={link_integrity.get('files_checked', 'n/a')}\n")
    fp.write(f"- link_integrity_broken_links={link_integrity.get('broken_links', 'n/a')}\n")
    fp.write(f"- command_refs_status={payload.get('statuses', {}).get('command_references', 'n/a')}\n")
    baseline_enabled = command_refs.get('baseline_enabled', 'n/a')
    if isinstance(baseline_enabled, bool):
        baseline_enabled = str(baseline_enabled).lower()
    fp.write(f"- command_refs_baseline_enabled={baseline_enabled}\n")
    fp.write(f"- command_refs_baseline_entries={command_refs.get('baseline_entries', 'n/a')}\n")
    fp.write(f"- command_refs_files_checked={command_refs.get('files_checked', 'n/a')}\n")
    fp.write(f"- command_refs_total_candidates={command_refs.get('total_candidates', 'n/a')}\n")
    fp.write(f"- command_refs_candidates_inline_code={command_refs.get('candidate_sources', {}).get('inline_code', 'n/a')}\n")
    fp.write(f"- command_refs_candidates_shell_block={command_refs.get('candidate_sources', {}).get('shell_block', 'n/a')}\n")
    fp.write(f"- command_refs_candidates_markdown_link={command_refs.get('candidate_sources', {}).get('markdown_link', 'n/a')}\n")
    fp.write(f"- command_refs_candidates_markdown_autolink={command_refs.get('candidate_sources', {}).get('markdown_autolink', 'n/a')}\n")
    fp.write(f"- command_refs_candidates_markdown_refdef={command_refs.get('candidate_sources', {}).get('markdown_refdef', 'n/a')}\n")
    fp.write(f"- command_refs_missing_references={command_refs.get('missing_references', 'n/a')}\n")
    fp.write(f"- docs_scorecard_status={payload.get('statuses', {}).get('docs_scorecard', 'n/a')}\n")
    fp.write(f"- scorecard_trend_status={payload.get('statuses', {}).get('scorecard_trend', 'n/a')}\n")
    fp.write(f"- scorecard_recency_status={payload.get('statuses', {}).get('scorecard_recency', 'n/a')}\n")
    fp.write(f"- scorecard_consistency_status={payload.get('statuses', {}).get('scorecard_consistency', 'n/a')}\n")
    fp.write(f"- scorecard_head_freshness_status={payload.get('statuses', {}).get('scorecard_head_freshness', 'n/a')}\n")
    fp.write(f"- scorecard_timestamp_format_status={payload.get('statuses', {}).get('scorecard_timestamp_format', 'n/a')}\n")
    fp.write(f"- scorecard_delta_artifact_status={payload.get('statuses', {}).get('scorecard_delta_artifact', 'n/a')}\n")
    fp.write(f"- scorecard_generation_drift_status={payload.get('statuses', {}).get('scorecard_generation_drift', 'n/a')}\n")
