#!/usr/bin/env bash
# Seeded-defect self-test for verify-theming-generated-artifacts.sh.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
VERIFY="$ROOT_DIR/scripts/qa/verify-theming-generated-artifacts.sh"

tmpdir="$(mktemp -d -t verify-theming-artifacts.XXXXXX)"
trap 'rm -rf "$tmpdir"' EXIT

mkdir -p \
  "$tmpdir/scripts/branding" \
  "$tmpdir/docs/reference/architecture" \
  "$tmpdir/deploy/k8s/base/apps/openedx/theme" \
  "$tmpdir/infrastructure/tutor/themes/mereka/scss" \
  "$tmpdir/infrastructure/tutor/themes/mereka/common/static/css" \
  "$tmpdir/infrastructure/tutor/themes/mereka/common/templates" \
  "$tmpdir/infrastructure/tutor/themes/mereka/lms/static/css" \
  "$tmpdir/infrastructure/tutor/themes/mereka/lms/templates" \
  "$tmpdir/infrastructure/tutor/themes/mereka/cms/static/css" \
  "$tmpdir/infrastructure/tutor/themes/mereka/cms/templates" \
  "$tmpdir/infrastructure/tutor/themes/mereka/mfe/theme"

cat >"$tmpdir/scripts/branding/generate-tokens-from-canonical.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
[[ "${1:-}" == "--check" ]]
EOF

cat >"$tmpdir/scripts/branding/build-tokens.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
[[ "${1:-}" == "--check" ]]
EOF

chmod +x "$tmpdir/scripts/branding/generate-tokens-from-canonical.sh" "$tmpdir/scripts/branding/build-tokens.sh"

cat >"$tmpdir/docs/reference/architecture/THEMING_GENERATED_ARTIFACT_CONTRACT.md" <<'EOF'
# Contract

Run `build-tokens.sh --check`.
Run `generate-tokens-from-canonical.sh --check`.

## Exit Criteria
- Drift checks pass.

## Runtime Shim Ownership
- `head-extra.html` remains loader-only.

## Head-Extra Runtime Shims
- `deploy/k8s/base/apps/openedx/theme/head-extra.html`
- `infrastructure/tutor/themes/mereka/common/templates/head-extra.html`
- `infrastructure/tutor/themes/mereka/lms/templates/head-extra.html`
- `infrastructure/tutor/themes/mereka/cms/templates/head-extra.html`
EOF

cat >"$tmpdir/infrastructure/tutor/themes/mereka/scss/_tokens.scss" <<'EOF'
/* BEGIN GENERATED */
EOF

cat >"$tmpdir/infrastructure/tutor/themes/mereka/common/static/css/mereka-design-tokens.css" <<'EOF'
/* DO NOT EDIT */
EOF

for override in \
  "$tmpdir/infrastructure/tutor/themes/mereka/common/static/css/mereka-overrides.css" \
  "$tmpdir/infrastructure/tutor/themes/mereka/lms/static/css/mereka-overrides.css" \
  "$tmpdir/infrastructure/tutor/themes/mereka/cms/static/css/mereka-overrides.css"; do
  cat >"$override" <<'EOF'
/* BEGIN GENERATED */
EOF
done

for css_file in \
  "$tmpdir/infrastructure/tutor/themes/mereka/mfe/theme/light.min.css" \
  "$tmpdir/infrastructure/tutor/themes/mereka/mfe/theme/mereka-brand.min.css" \
  "$tmpdir/infrastructure/tutor/themes/mereka/mfe/theme/mereka-brand-light.min.css"; do
  cat >"$css_file" <<'EOF'
/* Generated by build-tokens.sh */
EOF
done

cat >"$tmpdir/infrastructure/tutor/themes/mereka/mfe/theme/core.min.css" <<'EOF'
/* core payload */
EOF

cat >"$tmpdir/infrastructure/tutor/themes/mereka/README.md" <<'EOF'
# Mereka Theme

## Canonical Ownership
- generated token artifacts are owned by the branding generators
- `head-extra.html` files are runtime loader shims
EOF

cat >"$tmpdir/deploy/k8s/base/apps/openedx/theme/head-extra.html" <<'EOF'
<!-- runtime loader shim -->
EOF

cat >"$tmpdir/infrastructure/tutor/themes/mereka/common/templates/head-extra.html" <<'EOF'
<!-- runtime shim only -->
EOF

cat >"$tmpdir/infrastructure/tutor/themes/mereka/lms/templates/head-extra.html" <<'EOF'
<!-- runtime shim copy -->
EOF

cat >"$tmpdir/infrastructure/tutor/themes/mereka/cms/templates/head-extra.html" <<'EOF'
<!-- runtime shim only -->
EOF

run_expect_fail() {
  local label="$1"
  set +e
  REPO_ROOT_OVERRIDE="$tmpdir" bash "$VERIFY" >/tmp/verify-theming-generated.out 2>&1
  local rc=$?
  set -e
  if [[ "$rc" -eq 0 ]]; then
    echo "FAIL ${label}: expected failure but command succeeded" >&2
    cat /tmp/verify-theming-generated.out >&2 || true
    exit 1
  fi
  echo "PASS ${label}"
}

run_expect_pass() {
  local label="$1"
  REPO_ROOT_OVERRIDE="$tmpdir" bash "$VERIFY" >/tmp/verify-theming-generated.out 2>&1
  echo "PASS ${label}"
}

# Case 1: all generated markers present => pass.
run_expect_pass "complete generated-artifact contract passes"

# Case 2: seeded drift in generated marker => fail.
cat >"$tmpdir/infrastructure/tutor/themes/mereka/mfe/theme/light.min.css" <<'EOF'
/* missing generator header */
EOF
run_expect_fail "missing generated header is rejected"

echo "OK"
