#!/usr/bin/env bash
# @covers AC-TKN-033, AC-TKN-034
# @spec: paragon-design-tokens-migration_spec.md
set -euo pipefail

REPO_ROOT="${REPO_ROOT_OVERRIDE:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"

PASS=0
FAIL=0

pass() {
  echo "PASS $1"
  PASS=$((PASS + 1))
}

fail() {
  echo "FAIL $1"
  FAIL=$((FAIL + 1))
}

require_file() {
  local path="$1"
  local label="$2"
  if [[ -f "$path" ]]; then
    pass "$label exists"
  else
    fail "$label missing ($path)"
  fi
}

require_contains() {
  local path="$1"
  local pattern="$2"
  local label="$3"
  if [[ -z "$path" || ! -f "$path" ]]; then
    fail "$label (file not found)"
    return
  fi
  if rg -q "$pattern" "$path"; then
    pass "$label"
  else
    fail "$label"
  fi
}

echo "=== Theming Generated Artifact Contract ==="

CONTRACT_DOC_NEW="$REPO_ROOT/docs/concepts/architecture/THEMING_GENERATED_ARTIFACT_CONTRACT.md"
CONTRACT_DOC_LEGACY="$REPO_ROOT/docs/architecture/THEMING_GENERATED_ARTIFACT_CONTRACT.md"

if [[ -f "$CONTRACT_DOC_NEW" ]]; then
  CONTRACT_DOC="$CONTRACT_DOC_NEW"
  pass "generated-artifact contract doc exists (canonical path)"
elif [[ -f "$CONTRACT_DOC_LEGACY" ]]; then
  CONTRACT_DOC="$CONTRACT_DOC_LEGACY"
  pass "generated-artifact contract doc exists (legacy path)"
else
  fail "generated-artifact contract doc missing (checked $CONTRACT_DOC_NEW and $CONTRACT_DOC_LEGACY)"
  CONTRACT_DOC=""
fi

echo
echo "[1/4] Canonical token generator drift check"
if "$REPO_ROOT/scripts/branding/generate-tokens-from-canonical.sh" --check; then
  pass "generate-tokens-from-canonical.sh --check"
else
  fail "generate-tokens-from-canonical.sh --check"
fi

echo
echo "[2/4] Runtime theme generator drift check"
if "$REPO_ROOT/scripts/branding/build-tokens.sh" --check; then
  pass "build-tokens.sh --check"
else
  fail "build-tokens.sh --check"
fi

echo
echo "[3/4] Generated markers (no manual edits)"
require_contains \
  "$REPO_ROOT/infrastructure/tutor/themes/mereka/scss/_tokens.scss" \
  "BEGIN GENERATED" \
  "_tokens.scss has generated block marker"
require_contains \
  "$REPO_ROOT/infrastructure/tutor/themes/mereka/common/static/css/mereka-design-tokens.css" \
  "DO NOT EDIT" \
  "mereka-design-tokens.css has generated marker"

for overrides in \
  "$REPO_ROOT/infrastructure/tutor/themes/mereka/common/static/css/mereka-overrides.css" \
  "$REPO_ROOT/infrastructure/tutor/themes/mereka/lms/static/css/mereka-overrides.css" \
  "$REPO_ROOT/infrastructure/tutor/themes/mereka/cms/static/css/mereka-overrides.css"; do
  require_contains "$overrides" "BEGIN GENERATED" "$(basename "$overrides") has generated marker"
done

for css_file in \
  "$REPO_ROOT/infrastructure/tutor/themes/mereka/mfe/theme/light.min.css" \
  "$REPO_ROOT/infrastructure/tutor/themes/mereka/mfe/theme/mereka-brand.min.css" \
  "$REPO_ROOT/infrastructure/tutor/themes/mereka/mfe/theme/mereka-brand-light.min.css"; do
  require_contains "$css_file" "Generated by build-tokens.sh" "$(basename "$css_file") has generator header"
done

CORE_THEME="$REPO_ROOT/infrastructure/tutor/themes/mereka/mfe/theme/core.min.css"
require_file "$CORE_THEME" "core.min.css"
if [[ -s "$CORE_THEME" ]]; then
  pass "core.min.css is non-empty"
else
  fail "core.min.css is empty"
fi

echo
echo "[4/4] Contract doc cross-reference"
require_contains "$CONTRACT_DOC" "build-tokens.sh --check" "contract doc includes runtime drift command"
require_contains "$CONTRACT_DOC" "generate-tokens-from-canonical.sh --check" "contract doc includes canonical drift command"
require_contains "$CONTRACT_DOC" "Exit Criteria" "contract doc defines transition exit criteria"

echo
echo "Summary: PASS=${PASS} FAIL=${FAIL}"
if [[ "$FAIL" -gt 0 ]]; then
  exit 1
fi
