organizations:
  - short_name: MEREKA
    name: Mereka Academy
    description: Mereka Academy main site catalog.
  - short_name: BIJIBIJI
    name: Biji-Biji Academy
    description: Biji-Biji Academy microsite catalog.
  - short_name: SKILLOURFUTURE
    name: Skill Our Future
    description: Skill Our Future microsite catalog.

sites:
  - domain: academyv2.mereka.io
    name: Mereka Academy
    orgs:
      - MEREKA
    site_values:
      domain: academyv2.mereka.io
      site_name: Mereka Academy
      platform_name: Mereka Academy
      LMS_ROOT_URL: https://academyv2.mereka.io
      CMS_ROOT_URL: https://studio.academyv2.mereka.io
      MFE_BASE_URL: https://apps.academyv2.mereka.io
      THEME_NAME: mereka
      ENABLE_COMPREHENSIVE_THEMING: true
      course_org_filter:
        - MEREKA
      logo_image: https://academyv2.mereka.io/static/mereka/images/logo-horizontal.png
      logo_url: /
      favicon_path: mereka/images/favicon.ico
      homepage_banner_enabled: false

  - domain: academy.biji-biji.com
    name: Biji-Biji Academy
    orgs:
      - BIJIBIJI
    site_values:
      domain: academy.biji-biji.com
      site_name: Biji-Biji Academy
      platform_name: Biji-Biji Academy
      LMS_ROOT_URL: https://academy.biji-biji.com
      CMS_ROOT_URL: https://studio.academy.biji-biji.com
      MFE_BASE_URL: https://apps.academy.biji-biji.com
      THEME_NAME: mereka
      ENABLE_COMPREHENSIVE_THEMING: true
      course_org_filter:
        - BIJIBIJI
      logo_image: https://academyv2.mereka.io/static/mereka/images/logo-horizontal.png
      logo_url: /
      favicon_path: mereka/images/favicon.ico
      homepage_banner_enabled: false

  - domain: skillourfuture.academy.mereka.io
    name: Skill Our Future
    orgs:
      - SKILLOURFUTURE
    site_values:
      domain: skillourfuture.academy.mereka.io
      site_name: Skill Our Future
      platform_name: Skill Our Future
      LMS_ROOT_URL: https://skillourfuture.academy.mereka.io
      CMS_ROOT_URL: https://studio.skillourfuture.academy.mereka.io
      MFE_BASE_URL: https://apps.skillourfuture.academy.mereka.io
      THEME_NAME: mereka
      ENABLE_COMPREHENSIVE_THEMING: true
      course_org_filter:
        - SKILLOURFUTURE
      logo_image: https://academyv2.mereka.io/static/mereka/images/logo-horizontal.png
      logo_url: /
      favicon_path: mereka/images/favicon.ico
