organizations:
  - short_name: MEREKA
    name: Mereka Academy
    description: Mereka Academy main site catalog.
  - short_name: BIJIBIJI
    name: Biji-Biji Academy
    description: Biji-Biji Academy microsite catalog.
  - short_name: SKILLOURFUTURE
    name: Skill Our Future
    description: Skill Our Future microsite catalog.

sites:
  - domain: academyv2.mereka.dev
    name: Mereka Academy
    orgs:
      - MEREKA
    site_values:
      domain: academyv2.mereka.dev
      site_name: Mereka Academy
      platform_name: Mereka Academy
      LMS_ROOT_URL: https://academyv2.mereka.dev
      CMS_ROOT_URL: https://studio.academyv2.mereka.dev
      MFE_BASE_URL: https://apps.academyv2.mereka.dev
      THEME_NAME: mereka
      ENABLE_COMPREHENSIVE_THEMING: true
      course_org_filter:
        - MEREKA
      logo_image: https://academyv2.mereka.dev/static/mereka/images/logo-horizontal.svg
      logo_url: /
      favicon_path: mereka/images/favicon.ico
      homepage_banner_enabled: false
  - domain: preview.academyv2.mereka.dev
    name: Mereka Academy Preview
    orgs:
      - MEREKA
    site_values:
      domain: preview.academyv2.mereka.dev
      site_name: Mereka Academy Preview
      platform_name: Mereka Academy
      LMS_ROOT_URL: https://preview.academyv2.mereka.dev
      CMS_ROOT_URL: https://studio.academyv2.mereka.dev
      MFE_BASE_URL: https://apps.academyv2.mereka.dev
      THEME_NAME: mereka
      ENABLE_COMPREHENSIVE_THEMING: true
      course_org_filter:
        - MEREKA
      logo_image: https://preview.academyv2.mereka.dev/static/mereka/images/logo-horizontal.svg
      logo_url: /
      favicon_path: mereka/images/favicon.ico
      homepage_banner_enabled: false
