organizations:
  - short_name: MEREKA
    name: Mereka Academy
    description: Mereka Academy staging catalog.
  - short_name: BIJIBIJI
    name: Biji-Biji Academy
    description: Biji-Biji Academy microsite catalog.
  - short_name: SKILLOURFUTURE
    name: Skill Our Future
    description: Skill Our Future microsite catalog.

sites:
  - domain: staging.academyv2.mereka.io
    name: Mereka Academy
    orgs:
      - MEREKA
    site_values:
      domain: staging.academyv2.mereka.io
      site_name: Mereka Academy
      platform_name: Mereka Academy
      LMS_ROOT_URL: https://staging.academyv2.mereka.io
      CMS_ROOT_URL: https://staging.studio.academyv2.mereka.io
      MFE_BASE_URL: https://staging.apps.academyv2.mereka.io
      THEME_NAME: mereka
      ENABLE_COMPREHENSIVE_THEMING: true
      course_org_filter:
        - MEREKA
      logo_image: https://staging.academyv2.mereka.io/static/mereka/images/logo-horizontal.svg
      logo_url: /
      favicon_path: mereka/images/favicon.ico
      homepage_banner_enabled: false

  - domain: staging.preview.academyv2.mereka.io
    name: Mereka Academy Preview
    orgs:
      - MEREKA
    site_values:
      domain: staging.preview.academyv2.mereka.io
      site_name: Mereka Academy Preview
      platform_name: Mereka Academy
      LMS_ROOT_URL: https://staging.preview.academyv2.mereka.io
      CMS_ROOT_URL: https://staging.studio.academyv2.mereka.io
      MFE_BASE_URL: https://staging.apps.academyv2.mereka.io
      THEME_NAME: mereka
      ENABLE_COMPREHENSIVE_THEMING: true
      course_org_filter:
        - MEREKA
      logo_image: https://staging.preview.academyv2.mereka.io/static/mereka/images/logo-horizontal.svg
      logo_url: /
      favicon_path: mereka/images/favicon.ico
      homepage_banner_enabled: false
