apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp
  namespace: mereka-lms
spec:
  template:
    spec:
      containers:
        - name: smtp
          env:
            - name: SMARTHOST
              value: "email-smtp.ap-southeast-1.amazonaws.com::587"
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ses-smtp-credentials
                  key: RELAY_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ses-smtp-credentials
                  key: RELAY_PASSWORD
            - name: HOSTNAME
              value: "mail.staging.academy.mereka.io"
