apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
  labels:
    app.kubernetes.io/name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: bbi-k8
      secretVersionSelectionPolicy: LatestOrFail
      auth:
        workloadIdentity:
          clusterName: bbi-k8-cluster
          clusterLocation: asia-southeast1-c
          serviceAccountRef:
            name: external-secrets-gcp
            namespace: external-secrets
