"""
Video Analytics Models

Tracks video playback events and aggregates analytics data.

@spec: video-pipeline-delivery_spec.md (Phase 4)
@bead: mereka-lms-17jr
"""

from django.db import models
from django.conf import settings
from django.utils import timezone
from opaque_keys.edx.django.models import CourseKeyField
import logging

logger = logging.getLogger(__name__)

VIDEO_EVENT_TYPES = [
    ('played', 'Video Started/Played'),
    ('paused', 'Video Paused'),
    ('seeked', 'Video Seeked'),
    ('completed', 'Video Completed (90%+)'),
    ('ended', 'Video Ended'),
]


class VideoPlaybackEvent(models.Model):
    """
    Records individual video playback events from learners.

    Events are emitted from the Video XBlock client-side and stored here
    for analytics aggregation.

    Lifecycle:
    - Client emits event → POST /api/video/v1/events/
    - Event stored in DB
    - Daily Celery task aggregates into VideoAnalyticsSummary
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='video_playback_events',
        db_index=True,
        help_text='Learner who triggered the event'
    )

    course_key = CourseKeyField(
        max_length=255,
        db_index=True,
        help_text='Course containing the video'
    )

    video_id = models.CharField(
        max_length=255,
        db_index=True,
        help_text='Video identifier (playback_id or usage_key)'
    )

    event_type = models.CharField(
        max_length=20,
        choices=VIDEO_EVENT_TYPES,
        db_index=True,
        help_text='Type of playback event'
    )

    position = models.FloatField(
        help_text='Playback position in seconds when event occurred'
    )

    duration = models.FloatField(
        null=True,
        blank=True,
        help_text='Total video duration in seconds (if known)'
    )

    timestamp = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text='When the event occurred (UTC)'
    )

    org_slug = models.CharField(
        max_length=100,
        db_index=True,
        help_text='Organization slug for multi-tenant analytics'
    )

    # Additional context
    session_id = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        help_text='Session identifier for grouping events'
    )

    user_agent = models.CharField(
        max_length=500,
        null=True,
        blank=True,
        help_text='Client user agent string'
    )

    ip_address_hash = models.CharField(
        max_length=64,
        null=True,
        blank=True,
        help_text='SHA-256 hash of IP address (not plaintext)'
    )

    class Meta:
        verbose_name = 'Video Playback Event'
        verbose_name_plural = 'Video Playback Events'
        ordering = ['-timestamp']
        indexes = [
            models.Index(fields=['user', 'timestamp']),
            models.Index(fields=['course_key', 'video_id', 'timestamp']),
            models.Index(fields=['event_type', 'timestamp']),
            models.Index(fields=['org_slug', 'timestamp']),
        ]

    def __str__(self):
        return (
            f"VideoPlaybackEvent({self.event_type}, "
            f"video={self.video_id}, user={self.user.username}, "
            f"position={self.position:.1f}s)"
        )

    @classmethod
    def record_event(cls, user, course_key, video_id, event_type, position, **kwargs):
        """
        Create a video playback event.

        Args:
            user: User instance
            course_key: CourseKey instance
            video_id (str): Video identifier
            event_type (str): One of VIDEO_EVENT_TYPES
            position (float): Playback position in seconds
            **kwargs: Optional fields (duration, org_slug, session_id, etc.)

        Returns:
            VideoPlaybackEvent: Created event instance
        """
        event = cls.objects.create(
            user=user,
            course_key=course_key,
            video_id=video_id,
            event_type=event_type,
            position=position,
            duration=kwargs.get('duration'),
            org_slug=kwargs.get('org_slug', ''),
            session_id=kwargs.get('session_id'),
            user_agent=kwargs.get('user_agent'),
            ip_address_hash=kwargs.get('ip_address_hash'),
        )

        logger.info(
            f"Video event recorded: type={event_type}, video_id={video_id}, "
            f"user={user.username}, position={position:.1f}s"
        )

        return event


class VideoAnalyticsSummary(models.Model):
    """
    Daily aggregated analytics per video.

    Generated by Celery task that rolls up VideoPlaybackEvent data.

    Metrics:
    - play_count: Number of play events
    - unique_viewers: Distinct users who played
    - completion_count: Number of completion events (90%+)
    - completion_rate: completion_count / unique_viewers
    - avg_watch_time: Average watch duration per session
    - total_watch_time: Sum of all watch time
    """

    course_key = CourseKeyField(
        max_length=255,
        db_index=True,
        help_text='Course containing the video'
    )

    video_id = models.CharField(
        max_length=255,
        db_index=True,
        help_text='Video identifier'
    )

    org_slug = models.CharField(
        max_length=100,
        db_index=True,
        help_text='Organization slug'
    )

    date = models.DateField(
        db_index=True,
        help_text='Analytics date (UTC)'
    )

    # Engagement metrics
    play_count = models.IntegerField(
        default=0,
        help_text='Number of play events'
    )

    unique_viewers = models.IntegerField(
        default=0,
        help_text='Number of unique users who played'
    )

    completion_count = models.IntegerField(
        default=0,
        help_text='Number of users who completed (90%+)'
    )

    completion_rate = models.FloatField(
        default=0.0,
        help_text='Completion rate (0.0 - 1.0)'
    )

    # Watch time metrics (seconds)
    avg_watch_time = models.FloatField(
        default=0.0,
        help_text='Average watch duration per user (seconds)'
    )

    total_watch_time = models.FloatField(
        default=0.0,
        help_text='Total watch time across all users (seconds)'
    )

    # Quality metrics
    avg_position_reached = models.FloatField(
        default=0.0,
        help_text='Average furthest position reached (seconds)'
    )

    # Metadata
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text='When summary was generated'
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        help_text='When summary was last updated'
    )

    class Meta:
        verbose_name = 'Video Analytics Summary'
        verbose_name_plural = 'Video Analytics Summaries'
        unique_together = [('course_key', 'video_id', 'date')]
        ordering = ['-date', 'course_key', 'video_id']
        indexes = [
            models.Index(fields=['course_key', 'date']),
            models.Index(fields=['org_slug', 'date']),
            models.Index(fields=['video_id', 'date']),
        ]

    def __str__(self):
        return (
            f"VideoAnalyticsSummary({self.video_id}, date={self.date}, "
            f"views={self.play_count}, completion={self.completion_rate:.1%})"
        )

    @classmethod
    def aggregate_for_date(cls, date, course_key=None, video_id=None):
        """
        Aggregate video events for a specific date.

        Args:
            date: Date to aggregate (datetime.date)
            course_key (optional): Filter by course
            video_id (optional): Filter by video

        Returns:
            int: Number of summaries created/updated
        """
        from django.db.models import Count, Avg, Sum, Max, F
        from django.db.models.functions import Coalesce

        # Filter events for the target date
        events_qs = VideoPlaybackEvent.objects.filter(
            timestamp__date=date
        )

        if course_key:
            events_qs = events_qs.filter(course_key=course_key)
        if video_id:
            events_qs = events_qs.filter(video_id=video_id)

        # Group by course_key, video_id, org_slug
        grouped = events_qs.values('course_key', 'video_id', 'org_slug').distinct()

        summaries_created = 0

        for group in grouped:
            course_key_val = group['course_key']
            video_id_val = group['video_id']
            org_slug_val = group['org_slug']

            # Get events for this video on this date
            video_events = events_qs.filter(
                course_key=course_key_val,
                video_id=video_id_val
            )

            # Calculate metrics
            play_events = video_events.filter(event_type='played')
            play_count = play_events.count()
            unique_viewers = play_events.values('user').distinct().count()

            completion_events = video_events.filter(event_type='completed')
            completion_count = completion_events.values('user').distinct().count()

            completion_rate = (
                (completion_count / unique_viewers)
                if unique_viewers > 0 else 0.0
            )

            # Calculate watch time (sum of positions for completed events)
            watch_time_data = video_events.filter(
                event_type__in=['completed', 'ended', 'paused']
            ).aggregate(
                total_watch_time=Coalesce(Sum('position'), 0.0),
                avg_watch_time=Coalesce(Avg('position'), 0.0),
                avg_position=Coalesce(Avg('position'), 0.0),
            )

            # Create or update summary
            summary, created = cls.objects.update_or_create(
                course_key=course_key_val,
                video_id=video_id_val,
                date=date,
                defaults={
                    'org_slug': org_slug_val,
                    'play_count': play_count,
                    'unique_viewers': unique_viewers,
                    'completion_count': completion_count,
                    'completion_rate': completion_rate,
                    'avg_watch_time': watch_time_data['avg_watch_time'],
                    'total_watch_time': watch_time_data['total_watch_time'],
                    'avg_position_reached': watch_time_data['avg_position'],
                }
            )

            summaries_created += 1

            logger.info(
                f"Aggregated video analytics: video_id={video_id_val}, "
                f"date={date}, play_count={play_count}, "
                f"completion_rate={completion_rate:.1%}"
            )

        return summaries_created
