apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openedx-mfe
  namespace: mereka-lms
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: apps.academyv2.mereka.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
  tls:
    - hosts:
        - apps.academyv2.mereka.dev
      secretName: openedx-mfe-tls
