apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mereka-lms

resources:
  - ../../base
  - clusterissuer-letsencrypt-prod.yaml
  - ingress-openedx-lms.yaml

patchesStrategicMerge:
  - patches/domain-env.yaml
  - patches/clustersecretstore-gcp.yaml

# Use local images
images:
  - name: openedx
    newName: openedx
    newTag: latest
  - name: openedx-mfe
    newName: openedx-mfe
    newTag: latest

# Minimal replicas for local dev
replicas:
  - name: lms
    count: 1
  - name: cms
    count: 1
  - name: lms-worker
    count: 1
  - name: cms-worker
    count: 1
