---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
  labels:
    app.kubernetes.io/instance: mereka-lms
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/name: notes
    app.kubernetes.io/part-of: mereka-lms
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mereka-lms
      app.kubernetes.io/managed-by: tutor
      app.kubernetes.io/name: notes
      app.kubernetes.io/part-of: mereka-lms
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mereka-lms
        app.kubernetes.io/managed-by: tutor
        app.kubernetes.io/name: notes
        app.kubernetes.io/part-of: mereka-lms
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: notes
          image: docker.io/overhangio/openedx-notes:21.0.0
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: notesserver.settings.tutor
          envFrom:
            - secretRef:
                name: openedx-secrets
            - secretRef:
                name: database-secrets
          volumeMounts:
            - mountPath: /app/edx-notes-api/notesserver/settings/tutor.py
              name: settings
              subPath: tutor.py
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 15
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: settings
          configMap:
            name: notes-settings
