---
apiVersion: v1
kind: Service
metadata:
  name: notes
  labels:
    app.kubernetes.io/name: notes
    app.kubernetes.io/part-of: mereka-lms
spec:
  type: ClusterIP
  ports:
    - port: 8000
      name: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: notes
