apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
spec:
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
spec:
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-access-worker
spec:
  strategy:
    type: Recreate
